const menuData = [
    {
        id: 1,
        nombre: "Ensalada César",
        precio: 1200,
        categoria: "Entradas",
        descripcion:
            "Lechuga fresca, crutones, queso parmesano y aderezo César casero.",
        imagen: "https://imag.bonviveur.com/ensalada-cesar-casera.jpg",
    },
    {
        id: 2,
        nombre: "Carpaccio de Lomo",
        precio: 1500,
        categoria: "Entradas",
        descripcion:
            "Finas láminas de lomo con rúcula, queso parmesano y aceite de oliva.",
        imagen: "https://www.cucinare.tv/wp-content/uploads/2019/12/Dise%C3%B1o-sin-t%C3%ADtulo-7-4.png",
    },
    {
        id: 3,
        nombre: "Provoleta",
        precio: 1400,
        categoria: "Entradas",
        descripcion: "Queso provolone fundido con orégano y aceite de oliva.",
        imagen: "https://i0.wp.com/www.brasasysabores.com/wp-content/uploads/2017/11/Provoleta-el-queso-del-asado.jpg",
    },
    {
        id: 4,
        nombre: "Bife de Chorizo",
        precio: 4800,
        categoria: "Platos Principales",
        descripcion:
            "Jugoso bife de chorizo servido con papas fritas y ensalada.",
        imagen: "https://www.kingarthur.com.ar/wp-content/uploads/2016/01/CARNE-bife-chorizo-21.jpg",
    },
    {
        id: 5,
        nombre: "Milanesa Napolitana",
        precio: 3800,
        categoria: "Platos Principales",
        descripcion:
            "Milanesa de ternera con salsa de tomate, jamón y queso, con papas.",
        imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlAHaelvDmG0QRTk3P4k_H3xDagXzvYuT-zA&s",
    },
    {
        id: 6,
        nombre: "Salmón Grillado",
        precio: 5200,
        categoria: "Platos Principales",
        descripcion:
            "Filete de salmón a la parrilla con salsa de limón y puré.",
        imagen: "https://dcdn-us.mitiendanube.com/stores/001/622/600/products/salmon-rosado-grille1-06c9591946798934b716168667005820-640-0.jpg",
    },
    {
        id: 7,
        nombre: "Ñoquis de Papa",
        precio: 2800,
        categoria: "Pastas",
        descripcion: "Ñoquis caseros de papa con salsa a elección.",
        imagen: "https://www.unileverfoodsolutions.com.mx/dam/global-ufs/mcos/NOLA/calcmenu/recipes/MX-recipes/In-Development/FULL-GNOCCHIS.png",
    },
    {
        id: 8,
        nombre: "Tallarines a la Bolognesa",
        precio: 2900,
        categoria: "Pastas",
        descripcion: "Tallarines caseros con salsa de carne y parmesano.",
        imagen: "https://www.paulinacocina.net/wp-content/uploads/2015/05/bolo-1200x675.jpg",
    },
    {
        id: 9,
        nombre: "Flan Casero",
        precio: 1000,
        categoria: "Postres",
        descripcion: "Flan tradicional con caramelo y dulce de leche.",
        imagen: "https://img-global.cpcdn.com/recipes/95771e69abfbed20/680x482cq90/flan-casero-foto-principal.jpg",
    },
    {
        id: 10,
        nombre: "Tiramisú",
        precio: 1200,
        categoria: "Postres",
        descripcion:
            "Postre italiano con capas de bizcochuelo, café y mascarpone.",
        imagen: "https://www.paulinacocina.net/wp-content/uploads/2020/01/receta-de-tiramisu-facil-y-economico-1740483918-1200x675.jpg",
    },
    {
        id: 11,
        nombre: "Gaseosa Coca-Cola 500ml",
        precio: 900,
        categoria: "Bebidas",
        descripcion: "Coca-Cola, Sprite o Fanta (500ml).",
        imagen: "https://depositoelmayorista.com.ar/wp-content/uploads/2019/12/WhatsApp-Image-2020-02-14-at-18.54.52.jpeg",
    },
    {
        id: 12,
        nombre: "Agua Mineral",
        precio: 800,
        categoria: "Bebidas",
        descripcion: "Agua mineral con o sin gas (500ml).",
        imagen: "https://newbarmdp.com/wp-content/uploads/AGUA-MINERAL-KIN-500CC.-1.jpg",
    },
    {
        id: 13,
        nombre: "Lomito completo con papas fritas",
        precio: 3700,
        categoria: "Entradas",
        descripcion: "Pan, lomo, huevo, lechuga, tomate, mayonesa y papas.",
        imagen: "https://www.circuitogastronomico.com/wp-content/uploads/2023/04/pizzar-lomito-2.jpg",
    },
    {
        id: 14,
        nombre: "Cheesecake de Frutos Rojos",
        precio: 1300,
        categoria: "Postres",
        descripcion:
            "Tarta de queso con base de galleta y cobertura de frutos rojos.",
        imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4yaz_qCb-qKeWOTQCpeeCHwN7LkoGcCKvfw&s",
    },
    {
        id: 15,
        nombre: "Pizza Muzarella con Jamón y Morrones",
        precio: 4500,
        categoria: "Entradas",
        descripcion: "Pizza con salsa, muzzarella, jamón y morrones asados.",
        imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTT83k-Dw0oTvfqnpwDAG8cHvA_Z8_54LQ42g&s",
    },
];
